"""Add reference_url column to historical_event table

Revision ID: 49cc1858e10e
Revises: afecc8c433fe
Create Date: 2025-07-16 18:05:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49cc1858e10e'
down_revision = 'afecc8c433fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historical_event', sa.Column('reference_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historical_event', 'reference_url')
    # ### end Alembic commands ###